module.exports = {
  UNEXPECTED_ERROR: "[pixelic-api] Unexpected error!",
  INVALID_PIXELIC_API_KEY: "[pixelic-api] Unexpected error!",
  OPTIONS_MUST_BE_AN_OBJECT: "[pixelic-api] Client Options must be an Object!",
  RATELIMIT_MUST_BE_A_NUMBER: "[pixelic-api] Ratelimit Options must be Numbers!",
  CHECK_FOR_UPDATES_MUST_BE_A_BOOLEAN: "[pixelic-api] CheckForUpdates Option must be a Boolean!",
  INVALID_UUID_OR_USERNAME: "[pixelic-api] Invalid UUID or Username!",
  INVALID_UUID: "[pixelic-api] Invalid UUID!",
  INVALID_ISOSTRING: "[pixelic-api] Invalid ISO-String!",
  NOT_IN_DATABASE: "[pixelic-api] Player not found in the database!",
  GUILD_NOT_IN_DATABASE: "[pixelic-api] Guild not found in the database!",
  GUILD_MEMBER_NOT_IN_DATABASE: "[pixelic-api] Guild-Member not found in the database!",
  INVALID_GUILDID: "[pixelic-api] Invalid GuildID!",
  ALREADY_IN_DATABASE: "[pixelic-api] Player already in the database!",
  EMPTY_DATE: "[pixelic-api] No data was found for the specified date!",
  RATELIMIT: "[pixelic-api] Ratelimit has been exceeded",
  REDIS_HOST_MUST_BE_A_STRING: "[pixelic-api] Redis-Host must be a String!",
  REDIS_PORT_MUST_BE_A_NUMBER: "[pixelic-api] Redis-Port must be a Number!",
  REDIS_USERNAME_MUST_A_BE_STRING: "[pixelic-api] Redis-Username must be a String!",
  REDIS_PASSWORD_MUST_A_BE_STRING: "[pixelic-api] Redis-Password must be a String!",
  INVALID_HISTORY_TIMEFRAME: "[pixelic-api] Valid timeframes are : hour, day, week, month, year or alltime!",
  INVALID_HISTORY_STAT: "[pixelic-api] Valid Stats are : playersTracked, playersTrackedSkyblock, guildsTracked or auctionsStored!",
  INVALID_AH_HISTORY_TIMEFRAME: "[pixelic-api] Valid timeframes are : day, week, month, year or alltime!",
  INVALID_SKYBLOCK_ITEM: "[pixelic-api] Invalid Skyblock-Item ID!",
  INVALID_BAZAAR_PRODUCT: "[pixelic-api] This Skyblock-Item does not get sold on the Bazaar!",
  INVALID_AH_ITEM: "[pixelic-api] This Skyblock-Item is not getting sold on the Auctionhouse currently!",
  INVALID_LEADERBOARD_TIMEFRAME: "[pixelic-api] Invalid Leaderboard timeframe!",
  INVALID_LEADERBOARD: "[pixelic-api] Invalid Leaderboard!",
  INVALID_LEADERBOARD_LIMIT: "[pixelic-api] Invalid Leaderboard limit!",
  INVALID_PROFILE_UUID: "[pixelic-api] Invalid Profile UUID!",
  INVALID_ITEM_UUID: "[pixelic-api] Invalid Item UUID!",
  INVALID_AUCTION_UUID: "[pixelic-api] Invalid Auction UUID!",
  INVALID_DISTRIBUTION: "[pixelic-api] Valid distributions are : ranks, plusColor, plusPlusColor, language or chatChannel!",
};
